[package]
name = "clubhouse-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
serde = { version = "1.0.163", features = ["derive"] }
orion = "0.17.2"
base64 = "0.13.1"
