//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "media_node")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub media_slug: String,
    pub medium_type: i32,
    pub sort_key: i32,
    pub published: bool,
    pub archived: bool,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))")]
    pub created: Vec<u8>,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))")]
    pub updated: Vec<u8>,
    pub template: String,
    pub context: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
