//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_attributes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub uid: i32,
    pub display: String,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))")]
    pub created_at: Vec<u8>,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub last_login: Option<Vec<u8>>,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))")]
    pub last_updated: Vec<u8>,
    pub settings: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_email_password::Entity",
        from = "Column::Uid",
        to = "super::user_email_password::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserEmailPassword,
}

impl Related<super::user_email_password::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserEmailPassword.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
